### ISSUE TITLE
The new V3 Graphic Pack format

### ISSUE THREAD

**Issue by getdls** [slashiee/gfx_pack#1]
Peaked at Slashies Splatoon pack and updated rulesgen to match v3 rules. 
Run in the same folder as log.txt, (cemu root), default is set to x1 scaling to match new rule style. 

rules.txt has been updated, gitrules.txt hasn't.. waiting for the final build rules. 

updated -> Removed.. needs to be less crap before publishing.

**Comment by getdls** [comment]
Hmm something is funky with the scaling.. this WIP3 with old graphics pack.  
Similar results if i try to scale with new rules, wonder if need to account for full GX2SetScissor ? 

Also noted that rulesGen incorrectly scales 1920x1080.. I just used the 1280 as a template in the header instead of actually fetching values :/   Will be fixed if I can get things to scale correctly..

**Comment by getdls** [comment]
Yup, just rewrote the 360 -> 368 rule.. and now it scales correctly..   Why would old packs use the new GX2SetScissor logic?  A bunch of them will break. 

Then again, most of the GX2SetScissor calls probably round to the same number, so a search replace for all "new" resolutions will probably fix the issue. 
<img width="1014" alt="368" src="https://user-images.githubusercontent.com/25286924/43991071-35f1af32-9d65-11e8-85c3-5a044091c2ba.png">

**Comment by getdls** [comment]
aah, now I get it, there's one res for the 8 rounding and one for the viewport, and both need to be defined.

[TextureRedefine]
width = 448
height = 240
formats =  0x820
overwriteWidth = ($width / $gameWidth) * 428
overwriteHeight  = ($height/$gameHeight) * 240

[TextureRedefine]
width = 426
height = 240
formats =  0x820
overwriteWidth = ($width / $gameWidth) * 426
overwriteHeight  = ($height/$gameHeight) * 240


```
[TextureRedefine]
width = 320
height = 192
#formats =  0x816,0x01a
overwriteWidth = ($width / $gameWidth) * 320
overwriteHeight  = ($height/$gameHeight) * 192

[TextureRedefine]
width = 320
height = 180
#formats =  0x816,0x01a
overwriteWidth = ($width / $gameWidth) * 320
overwriteHeight  = ($height/$gameHeight) * 180
```
<img width="1920" alt="xcxscale" src="https://user-images.githubusercontent.com/25286924/43993778-2a3e075c-9d93-11e8-8164-da934db9cfcf.png">

**Comment by slashiee** [comment]
```[TextureRedefine]
width = 448
height = 240
formats =  0x820
overwriteWidth = ($width / $gameWidth) * 448
overwriteHeight  = ($height/$gameHeight) * 240```

**Comment by Crementif** [comment]
Yeah. I just want to share it in here since you might not know about what exactly happened yet.
![example image](https://user-images.githubusercontent.com/26669564/44000654-6ae82094-9e24-11e8-82b6-1a28e6433488.png)

So, basically, it's a pretty major update and this new repository should be used as a rework since we won't be able to just ship old packs with some variables changed.

Also, just wanna mention that Nsight also now shows texture information from Cemu so you can easily track which viewport or texture you're looking at. This is very handy for tracking the exact texture you're looking at in Nsight in the file dumps or in the new Texture Cache window in Cemu.

Some additional information about how I use these features:

First of all, you find a normal viewport in Nsight. I look what physical address this viewport has and search it in the Texture Cache window.
![texture cache - physical addresses highlighted](https://user-images.githubusercontent.com/26669564/44000722-878b8370-9e25-11e8-96f2-5312438b6c98.png)
Since they share the same physical address you can assume that the viewport size got accessed with a different resolution.

Just wanna mention that textures that show as mipmap's in Nsight are unrelated to this, that should just use old behavior (scaling mip00 should scale all of them just fine).

Also, feel free to edit/correct me or something, it's probably pretty unwelcoming stuff for anyone that would consider making a graphic pack themselves so I think we probably should make a wiki page like we had previously.

**Comment by getdls** [comment]
It's more work,  but the ability to see previous lookup is sooo much better than what we had before. 
I'd say it's even easier for someone new to understand. 

1. For most packs overwrite all calls not related to  0x31,0x32,0x33,0x34,0x35,0x431,0x432,0x433,0x434,0x435
2. Skip stuff that's 1:1 256x256
3. Skip anything below 160x90

And you should have a good start... the rest is just, open texture cache, check what formats are left, test, repeat.  We should have been nagging Exzap for better logging earlier, would have saved us a bunch of time on the BOTW stuff. 

Unfortunately there's no way to get the rounding part form logs right now, so rulesgen only gets you the basics.

**Comment by Crementif** [comment]
> What about vs/ps stuff? I don't see any way that they would extend the variables from rules.txt
What exactly do you mean?

**Comment by getdls** [comment]
I assume we want shaders to scale to the res the user selects. 
`R1f.y = R0f.y + intBitsToFloat(uf_remappedPS[0].y) / resXScale;`

We ca do sizeOf lookups.. but getting resXScale from rules.txt would be nicer..
Like 
```
[Preset]
name = Scale
$resXScale  = width  / gameWidth 
```

**Comment by Crementif** [comment]
Ah, yeah, that's indeed not supported. But, arithmetic stuff shouldn't be so difficult in OpenGL (unless we're dealing with preprocessor declarations like #define and such)

Also some noteworthiness information that might be handy in this situation is that by default it outputs doubles in the shaders and int's in the rules.txt file's. You can force ints in shaders by adding a `:int` like this in the preset declaration:
```
[Preset]
name = Scale
$resXScale:int = 300
```

It's all very simple "typing".

**Comment by Crementif** [comment]
I can't exactly find this "sizeOf" you're talking about, can you elaborate.

**Comment by getdls** [comment]
I haven't test it but maybe  textureSize(textureUnitPS0, 0) and/or uf_fragCoordScale would give us the actual res, not emulated.

**Comment by Crementif** [comment]
Both would result into their viewport resolution, pretty sure.

**Comment by getdls** [comment]
This doesn't work as expected, sticking it at the top rules.txt just disables all viewport rules
Anyone who knows if overwriteRelativeLodBias syntax has changed?

```
[TextureRedefine] #lod override, shimmer and possible sharper textures
formats  = 0x01a,0x31,0x32,0x33,0x34,0x35,0x431,0x432,0x433,0x434,0x435
overwriteRelativeLodBias = -8 #
```

**Comment by slashiee** [comment]
remove 0x1a

**Comment by getdls** [comment]
Breaks either way
```
[TextureRedefine] #lod override, shimmer and possible sharper textures
formats  = 0x433
overwriteLodBias = -8 #
```
```
[TextureRedefine] #lod override, shimmer and possible sharper textures
formats  = 0x433
overwriteRelativeLodBias = -8 #
```

**Comment by getdls** [comment]
Looks like it's unsigned int only :(  

This just  throws 

>  [18:31:11] graphicPack: can't parse preset "LOD -4": not enough parameters for equation

As soon as you asign anything but positive values
```
[Definition]
titleIds = 00050000101ED700,00050000101ED800,0005000010131D00
name = Negative texture LOD bias
path = "Tokyo Mirage Sessions FE/Graphics/Negative Texture LOD" 
description = Texture LOD override, possible shimmer but sharper textures
version = 3

[Preset]
name = LOD -4
$LOD = (-4)

[Preset]
name = LOD -1
$LOD = (-4)

[Preset]
name = LOD -2
$LOD = (-4)

[Preset]
name = LOD -4
$LOD = (-4)

[Preset]
name = LOD -8
$LOD = (-4)

[Preset]
name = LOD -8
$LOD = (-16)

[TextureRedefine]
formats = 0x01a,0x31,0x32,0x33,0x34,0x35,0x431,0x432,0x433,0x434,0x435
overwriteRelativeLodBias = $LOD

```

**Comment by getdls** [comment]
copy paste from pull request. Maybe you guys already have settled this? 

Since we’re going towards a PC config style with resolutions..why not continue along that line? Now that we can expand the menu settings per game, it won’t be as crowded. I figured anything that changes graphics sorts under graphics, PC game style.

When you expand graphics it easy to see what's active. This would include clarity, no-Gui, shadows, wide screen etc

I would separate work arounds and gameplay settings as they potentially break stuff when active. Nvida/AMD fixes, 60 fps, cheats

So I end up with game/graphics/... and game/modification or gameplay (or some better name)

**Comment by Crementif** [comment]
Hm, the less drop downs the better. I think we should probably stick with what we've got right now.

**Comment by getdls** [comment]
Thinking about it I'd prefer a flat structure..
<img width="739" alt="flat" src="https://user-images.githubusercontent.com/25286924/44162889-f25b4480-a0c1-11e8-859c-4a1268e4d687.png">

 No need to expand a bunch of menus, easy to debug whats active. With the exception of BOTW, it should be simpler (keep that as a separate workaround folder).   If you need further info about the option, the description box should cover that.

**Comment by getdls** [comment]
Looks like Ninja Gaiden is testing the classic comment injection on cemu!  ;)
<img width="464" alt="charinject" src="https://user-images.githubusercontent.com/25286924/44307571-bca9aa80-a3a4-11e8-8976-f0f55c120a9c.png">


I do hope Exzap has salted his keys

**Comment by getdls** [comment]
I'd say that's a promising start...
<img width="960" alt="twilightfx" src="https://user-images.githubusercontent.com/25286924/44556490-4dcca880-a73a-11e8-8037-221b4c850862.png">

**Comment by getdls** [comment]
Are you guys running into general instability ?

Running a very basic rules.txt only scaling 1920x1080 I find that simply launching a game with resolution pack hangs like 1/5 of the time.. Or if I let the intro demo of twilight princess run for about 10 minutes, it usually hangs when looping?

**Comment by Crementif** [comment]
Hm, I've noticed not that much myself.
