### ISSUE TITLE
Super Mario 3D World has a few broken areas

### ISSUE THREAD

**Issue by legend800** [slashiee/gfx_pack#10]
Played for a few hours today and spotted a couple issues in 5-4 and 5-[]. Using Cemu 1.14 @ 2160 res., gfx pack as of 9/2.

![2018-09-02_21_58_10-cemu_1 14 0_wip_release_6_patreon_build_-_verified_-_fps__59 50_nvidia_gpu](https://user-images.githubusercontent.com/20983844/44970672-ba4c6200-af07-11e8-8116-e6405532ddef.png)

![2018-09-02_22_19_02-cemu_1 14 0_wip_release_6_patreon_build_-_verified_-_fps__60 00_nvidia_gpu](https://user-images.githubusercontent.com/20983844/44970673-ba4c6200-af07-11e8-8492-6028147eff13.png)

**Comment by getdls** [comment]
Hi
Forgot to commit Cpt toad fixes to SM3DW, they are in the pull request. Should fix above issue and some other minor stuff like zoom. 

![sm3dw2](https://user-images.githubusercontent.com/25286924/44995592-fe8d4000-afa3-11e8-8f39-173ac1771a0a.jpg)

**Comment by legend800** [comment]
Confirmed fix. Thanks!
