### ISSUE TITLE
BOTW Everything Blacked Out on Resolution Pack Rel 87

### ISSUE THREAD

**Issue by Nerenye** [slashiee/gfx_pack#14]
Hi There,

Having Problems with Botw. Despite the Menue its not rendering Anything with activated resolution Pack.
GPU = Rx Vega 64 
Cpu = i5 6600k @ 5Ghz
Ram = 16Gb

Deleted all Packs Several Times an tried the last 4 Releases.

**Comment by slashiee** [comment]
#7
