### ISSUE TITLE
Graphic Pack 97 FPS++ BOTW no 60 fps anymore

### ISSUE THREAD

**Issue by Ludhelm** [slashiee/gfx_pack#18]
With the pack 87 fps++ works just fine and i get stable 60 fps @ 4k.
Now after i updated directly to 97 fps++ dont work anymore.
(Static 60fps dont work also)

**Comment by phush0** [comment]
for me too, massive drop in framerate from 60fps to 15-20

**Comment by Ludhelm** [comment]
Thx till now i just used the FPS++ folder from pack 87. Only thing now is that the order in graphic packs menu isnt correct. Now it is at  "old packs" again.

**Comment by Crementif** [comment]
Don't use the pre-release versions! It's not very clear, true
