### ISSUE TITLE
Shaders not scaling

### ISSUE THREAD

**Issue by slashiee** [slashiee/gfx_pack#25]
At least with 1.17.0 and the current version of 1.17.1, shaders are not scaling in version 5 packs.

<img width="886" alt="2020-01-21_19-41-55" src="https://user-images.githubusercontent.com/15317421/72863676-58b89f00-3c86-11ea-9a35-73df47bc8184.png">

<img width="845" alt="2020-02-07_17-56-13" src="https://user-images.githubusercontent.com/15317421/74077276-4901c000-49d3-11ea-812e-95bcfdc34c0d.png">

**Comment by Crementif** [comment]
[Fixed in Cemu 1.17.2](http://bugs.cemu.info/issues/270/)
